# syntax=docker/dockerfile:1.4
# Fast build: copies pre-built binary from host instead of compiling
# in container. Uses patchelf to fix the NixOS interpreter and rpath.
#
# Usage:
#   make docker-build-bpfman-fast
#
# Requires:
#   make bpfman-build

ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM ${BASE_IMAGE}

COPY bin/bpfman-portable /bpfman

ENV BPFMAN_MODE=bpfman-rpc
ENV BPFMAN_PPROF_ADDRESS=localhost:6060
ENTRYPOINT ["/bpfman"]
