// Command parity-readme generates the Rust parity section of the
// repository README from docs/parity/cases.yaml and the captured
// transcripts under docs/parity/outputs/.
//
// The tables and prose come from cases.yaml. Each proof anchor's inline
// command output is extracted live from the named transcript, so the
// values shown in the README are real captured numbers rather than
// hand-typed. A field that no longer appears in a transcript is a hard
// error, so a stale or re-captured transcript fails the build.
//
// Usage:
//
//	parity-readme            rewrite the section in place
//	parity-readme -check     exit non-zero if the section is stale
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/frobware/go-bpfman/internal/parity"

	"gopkg.in/yaml.v3"
)

const (
	beginMarker = "<!-- BEGIN GENERATED RUST PARITY -->"
	endMarker   = "<!-- END GENERATED RUST PARITY -->"
)

type cases struct {
	Meta struct {
		RustRevision string `yaml:"rust_revision"`
		RustVersion  string `yaml:"rust_version"`
		GoRevision   string `yaml:"go_revision"`
		Kernel       string `yaml:"kernel"`
	} `yaml:"meta"`
	Coverage []struct {
		Area    string `yaml:"area"`
		State   string `yaml:"state"`
		Verdict string `yaml:"verdict"`
	} `yaml:"coverage"`
	Programs []struct {
		Type  string `yaml:"type"`
		Go    string `yaml:"go"`
		Rust  string `yaml:"rust"`
		Flags string `yaml:"flags"`
		Gaps  string `yaml:"gaps"`
	} `yaml:"programs"`
	FlagCoverage []struct {
		Area   string `yaml:"area"`
		Status string `yaml:"status"`
	} `yaml:"flag_coverage"`
	Differences []string            `yaml:"differences"`
	KernelCases []parity.KernelCase `yaml:"kernel_cases"`
	Anchors     []anchor            `yaml:"anchors"`
}

type anchor struct {
	ID             string `yaml:"id"`
	Object         string `yaml:"object"`
	Intro          string `yaml:"intro"`
	Result         string `yaml:"result"`
	GoTranscript   string `yaml:"go_transcript"`
	RustTranscript string `yaml:"rust_transcript"`
	Steps          []step `yaml:"steps"`
}

type step struct {
	GoCmd      string   `yaml:"go_cmd"`
	GoLocate   string   `yaml:"go_locate"`
	GoFields   []string `yaml:"go_fields"`
	RustCmd    string   `yaml:"rust_cmd"`
	RustLocate string   `yaml:"rust_locate"`
	RustFields []string `yaml:"rust_fields"`
}

func main() {
	check := flag.Bool("check", false, "exit non-zero if the README section is stale instead of rewriting it")
	casesPath := flag.String("cases", "docs/parity/cases.yaml", "path to the cases manifest")
	readmePath := flag.String("readme", "README.md", "path to the README to update")
	flag.Parse()

	if err := run(*casesPath, *readmePath, *check); err != nil {
		fmt.Fprintln(os.Stderr, "parity-readme:", err)
		os.Exit(1)
	}
}

func run(casesPath, readmePath string, check bool) error {
	raw, err := os.ReadFile(casesPath)
	if err != nil {
		return err
	}
	var c cases
	if err := yaml.Unmarshal(raw, &c); err != nil {
		return fmt.Errorf("parse %s: %w", casesPath, err)
	}

	section, err := render(&c, filepath.Dir(casesPath))
	if err != nil {
		return err
	}

	readme, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	updated, err := splice(string(readme), section)
	if err != nil {
		return err
	}

	if check {
		if updated != string(readme) {
			return fmt.Errorf("%s parity section is stale; run `make parity-readme`", readmePath)
		}
		return nil
	}
	if updated == string(readme) {
		fmt.Println("parity-readme: README already up to date")
		return nil
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		return err
	}
	fmt.Printf("parity-readme: updated %s\n", readmePath)
	return nil
}

// splice replaces the marker-bounded region of readme with section.
func splice(readme, section string) (string, error) {
	b := strings.Index(readme, beginMarker)
	e := strings.Index(readme, endMarker)
	if b < 0 || e < 0 || e < b {
		return "", fmt.Errorf("markers %q / %q not found in README", beginMarker, endMarker)
	}
	return readme[:b] + section + readme[e+len(endMarker):], nil
}

func render(c *cases, baseDir string) (string, error) {
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	p("%s\n", beginMarker)
	p("## Rust parity\n\n")
	p("<!-- Generated by `make parity-readme` from docs/parity/cases.yaml and\n")
	p("     the transcripts under docs/parity/outputs/. Do not edit this\n")
	p("     section by hand; edit cases.yaml and regenerate. -->\n\n")

	p("go-bpfman aims for behavioural parity with Rust bpfman across the shared\n")
	p("CLI surface: `load`, `attach`, `detach`, `unload`, `list`, `get`. This\n")
	p("section records reproducible evidence for that aim, comparing the two\n")
	p("implementations on the same BPF object files and commands. The full\n")
	p("evidence -- raw transcripts, the driver scripts, and the detailed\n")
	p("findings -- lives under [`docs/parity/`](docs/parity/).\n\n")

	p("Scope is CLI only: gRPC, the operator, and image-build flows are not\n")
	p("covered here. Compared against Rust bpfman `%s` (`%s`)\n", c.Meta.RustRevision, c.Meta.RustVersion)
	p("and go-bpfman `%s`, on Linux %s.\n\n", c.Meta.GoRevision, c.Meta.Kernel)

	p("### Coverage at a glance\n\n")
	p("| Area | State | Verdict |\n| --- | --- | --- |\n")
	for _, cv := range c.Coverage {
		p("| %s | %s | %s |\n", cv.Area, cv.State, cv.Verdict)
	}
	p("\n")
	p("`State` is the column to scan for remaining work: `proven` means parity\n")
	p("is computed and gated by `cmd/parity-compare`; `not tested` means this\n")
	p("evidence does not yet cover it. The not-tested surfaces exist in both\n")
	p("implementations -- `not tested` is about parity evidence, not whether\n")
	p("go-bpfman implements them. `Verdict` summarises who is ahead where they\n")
	p("differ: `parity` (equal), `Go ahead` (Go demonstrably correct, Rust\n")
	p("wrong), `unclear` (differ with no demonstrable right answer), `Go-only`\n")
	p("(Rust unsupported). No case was found where Rust is ahead of Go.\n\n")

	// Kernel-judged verdicts, computed from the captured bpftool
	// footprints so the parity column is derived, not asserted. A
	// missing footprint or a verdict that contradicts its declared
	// expectation fails generation.
	kernelDir := filepath.Join(baseDir, "outputs", "kernel")
	kverdict := map[string]string{}
	for _, kc := range c.KernelCases {
		diffs, err := parity.Compare(kernelDir, kc.Case)
		if err != nil {
			return "", fmt.Errorf("kernel case %q: %w", kc.Case, err)
		}
		if v, ok := parity.Judge(kc, diffs); !ok {
			return "", fmt.Errorf("kernel case %q contradicts its expectation: %s", kc.Case, v)
		}
		if len(diffs) == 0 {
			kverdict[kc.Case] = "match"
		} else {
			kverdict[kc.Case] = "differ: " + strings.Join(parity.Paths(diffs), ", ")
		}
	}

	p("### Support\n\n")
	p("| Program type | Go lifecycle | Rust lifecycle | Kernel (bpftool) | Flag coverage | Gaps |\n")
	p("| --- | --- | --- | --- | --- | --- |\n")
	for _, pr := range c.Programs {
		kv := kverdict[pr.Type]
		if kv == "" {
			kv = "-"
		}
		p("| %s | %s | %s | %s | %s | %s |\n", pr.Type, pr.Go, pr.Rust, kv, pr.Flags, pr.Gaps)
	}
	p("\n")
	p("\"Lifecycle\" is `load -> get program -> attach -> get link -> list ->\n")
	p("detach -> unload`, compared on normalised semantic state. The \"Kernel\n")
	p("(bpftool)\" column is computed, not asserted: `parity-compare` captures\n")
	p("each program's kernel + bpffs footprint with `bpftool` (program tag,\n")
	p("map shape, link semantics) for both implementations and diffs them, so\n")
	p("`match` means the kernel objects are identical and `differ` names the\n")
	p("exact field. \"downgraded\" means the command succeeds but Rust produces\n")
	p("an entry probe rather than a return probe.\n\n")

	p("### Flag coverage\n\n")
	p("| Area | Status |\n| --- | --- |\n")
	for _, f := range c.FlagCoverage {
		p("| %s | %s |\n", f.Area, f.Status)
	}
	p("\n")

	p("### Known differences\n\n")
	p("The differences, with reproductions and a note on what \"divergence\"\n")
	p("does and does not claim, are in\n")
	p("[`docs/parity/ISSUES.md`](docs/parity/ISSUES.md). In short:\n\n")
	for _, d := range c.Differences {
		p("- %s\n", d)
	}
	p("\n")

	for _, a := range c.Anchors {
		if err := renderAnchor(&b, a, baseDir); err != nil {
			return "", err
		}
	}

	p("### Reproducing\n\n")
	p("Build the `bin/go-bpfman` and `bin/bpfman-rs` symlinks, then run\n")
	p("`bash docs/parity/run-all.sh`. Details, including the host assumptions\n")
	p("and the interface and namespace setup recipes, are in\n")
	p("[`docs/parity/README.md`](docs/parity/README.md) and\n")
	p("[`docs/parity/ENVIRONMENT.md`](docs/parity/ENVIRONMENT.md).\n")
	p("%s", endMarker)
	return b.String(), nil
}

func renderAnchor(b *strings.Builder, a anchor, baseDir string) error {
	p := func(format string, x ...any) { fmt.Fprintf(b, format, x...) }
	p("### Proof: %s\n\n", a.ID)
	p("Shared object `%s`, %s Excerpts below; full output in the linked transcripts.\n\n", a.Object, a.Intro)

	goBlock, err := renderSteps(filepath.Join(baseDir, a.GoTranscript), a.Steps, true)
	if err != nil {
		return fmt.Errorf("anchor %q (go): %w", a.ID, err)
	}
	rustBlock, err := renderSteps(filepath.Join(baseDir, a.RustTranscript), a.Steps, false)
	if err != nil {
		return fmt.Errorf("anchor %q (rust): %w", a.ID, err)
	}

	p("Go:\n\n```console\n%s```\n\n", goBlock)
	p("Rust:\n\n```console\n%s```\n\n", rustBlock)

	goLink := "docs/parity/" + a.GoTranscript
	rustLink := "docs/parity/" + a.RustTranscript
	p("Result: %s. Full transcripts:\n", a.Result)
	p("[`%s`](%s),\n", filepath.Base(a.GoTranscript), goLink)
	p("[`%s`](%s).\n\n", filepath.Base(a.RustTranscript), rustLink)
	return nil
}

// renderSteps emits, for each step, the curated command followed by the
// matching field lines pulled from the transcript, framed by "..." to
// signal that the output is excerpted.
func renderSteps(transcript string, steps []step, isGo bool) (string, error) {
	var b strings.Builder
	for _, s := range steps {
		cmd, locate, fields := s.RustCmd, s.RustLocate, s.RustFields
		if isGo {
			cmd, locate, fields = s.GoCmd, s.GoLocate, s.GoFields
		}
		block, err := extractBlock(transcript, locate)
		if err != nil {
			return "", err
		}
		lines, err := pickFields(block, fields, isGo)
		if err != nil {
			return "", fmt.Errorf("%s (locate %q): %w", transcript, locate, err)
		}
		fmt.Fprintf(&b, "$ %s\n...\n", cmd)
		for _, ln := range lines {
			fmt.Fprintf(&b, "%s\n", ln)
		}
		b.WriteString("...\n")
	}
	return b.String(), nil
}

// extractBlock returns the output lines of the transcript command whose
// "$ ..." line contains locate, up to the trailing "[exit N]" line.
func extractBlock(path, locate string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	lines := strings.Split(string(data), "\n")
	start := -1
	for i, ln := range lines {
		if strings.HasPrefix(ln, "$ ") && strings.Contains(ln, locate) {
			start = i
			break
		}
	}
	if start < 0 {
		return nil, fmt.Errorf("command matching %q not found in %s", locate, path)
	}
	var block []string
	for i := start + 1; i < len(lines); i++ {
		if strings.HasPrefix(lines[i], "[exit") {
			break
		}
		block = append(block, lines[i])
	}
	return block, nil
}

// pickFields returns the first transcript line containing each field
// pattern, in order. Go (JSON) lines are trimmed of indentation; Rust
// (padded text) lines are trimmed and their padding collapsed.
func pickFields(block, fields []string, isGo bool) ([]string, error) {
	out := make([]string, 0, len(fields))
	for _, f := range fields {
		var found string
		for _, ln := range block {
			if strings.Contains(ln, f) {
				found = ln
				break
			}
		}
		if found == "" {
			return nil, fmt.Errorf("field %q not present (transcript changed?)", f)
		}
		if isGo {
			found = strings.TrimSpace(found)
		} else {
			found = collapseSpaces(found)
		}
		out = append(out, found)
	}
	return out, nil
}

func collapseSpaces(s string) string {
	s = strings.TrimSpace(s)
	var b strings.Builder
	space := false
	for _, r := range s {
		if r == ' ' {
			if !space {
				b.WriteByte(' ')
			}
			space = true
			continue
		}
		space = false
		b.WriteRune(r)
	}
	return b.String()
}
