apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/frobware/go-bpfman?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && (".tekton/***".pathChanged() || "Containerfile.bpfman.openshift".pathChanged()
      || "cmd/***".pathChanged() || "dispatcher/***".pathChanged() || "go.mod".pathChanged()
      || "go.sum".pathChanged() || "Makefile".pathChanged() || "vendor/***".pathChanged()
      || "manager/***".pathChanged() || "interpreter/***".pathChanged()
      || "kernel/***".pathChanged() || "action/***".pathChanged()
      || "server/***".pathChanged() || "lock/***".pathChanged()
      || "version/***".pathChanged() || "LICENSE".pathChanged()
      || "OPENSHIFT-VERSION".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: go-bpfman
    appstudio.openshift.io/component: go-bpfman
    pipelines.appstudio.openshift.io/type: build
  name: go-bpfman-on-pull-request
  namespace: ocp-bpfman-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-bpfman-tenant/go-bpfman:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.bpfman.openshift
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: '[{"type": "rpm", "path": "."}]'
  - name: build-args
    value:
    - BUILD_COMMIT={{revision}}
    - BUILD_BRANCH={{source_branch}}
    - BUILD_VERSION={{revision}}
  - name: build-args-file
    value: OPENSHIFT-VERSION
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-go-bpfman
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
